# Main endpoints (usually I don't write DELETE, PATCH, PUT methods, only in special cases)

### List all the news
GET http://127.0.0.1/api/news

### Create new News
POST http://127.0.0.1/api/news/
Content-Type: application/json
Authorization: Token 1fa8698661a1be782368cb7dd9e464d18226ad7a

{
    "title": "title",
    "content": "content"
}

### Create new News (error 400 due to token missing)
POST http://127.0.0.1/api/news/
Content-Type: application/json

{
    "title": "title",
    "content": "content"
}

### Create new News (error 400 due to data missing)
POST http://127.0.0.1/api/news/

### List all comments of News with news_id=1
GET http://127.0.0.1/api/news/1/comments

### List all users
GET http://127.0.0.1/api/users

### Get one user
GET http://127.0.0.1/api/users/1

###
GET http://127.0.0.1/api/authors

###
GET http://127.0.0.1/api/authors/1

###
POST http://127.0.0.1/api/authors/
Authorization: Token 1fa8698661a1be782368cb7dd9e464d18226ad7a
Content-Type: application/json

{
    "name": "demian",
    "surname": "komarov",
    "age": 17
}


# Moderating functionality

### List all unmoderated News
GET http://127.0.0.1/api/news/moderate


### Approve News with news_id=1 (is_moderated=True)
POST http://127.0.0.1/api/news/1/approve/


# Tokens and users

###
GET http://127.0.0.1/api/users/

###
POST http://127.0.0.1/api/users/
Content-Type: application/json

{
    "email": "kdemian@yandex.ru",
    "password": "demian197"
}

###
POST http://127.0.0.1/api/auth/token/login/
Content-Type: application/json

{
    "email": "kdemian@yandex.ru",
    "password": "demian"
}


# Profile

###
GET http://127.0.0.1/api/users/profile
Authorization: Token 1fa8698661a1be782368cb7dd9e464d18226ad7a


# Comments

###
GET http://127.0.0.1/api/news/1/comments

### Create new News
POST http://127.0.0.1/api/news/
Content-Type: application/json
Authorization: Token 1fa8698661a1be782368cb7dd9e464d18226ad7a

{
    "title": "title",
    "content": "content"
}

### Create new comment for news with id=1
POST http://127.0.0.1/api/news/1/comments/
Content-Type: application/json
Authorization: Token 1fa8698661a1be782368cb7dd9e464d18226ad7a

{
    "text": "comment"
}

### Change news with id=1 on News with id=1
PATCH http://127.0.0.1/api/news/1/comments/1/
Content-Type: application/json
Authorization: Token 1fa8698661a1be782368cb7dd9e464d18226ad7a

{
    "text": "COMMENT"
}

### Change news with id=1 on News with id=1
PUT http://127.0.0.1/api/news/1/comments/1/
Content-Type: application/json
Authorization: Token 1fa8698661a1be782368cb7dd9e464d18226ad7a

{
    "text": "NEW COMMENT"
}
