# Generated by Django 4.2.2 on 2023-07-02 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(help_text='Уникальный идентификатор новости', primary_key=True, serialize=False, verbose_name='ID книги')),
                ('title', models.CharField(help_text='Заголовок новости', max_length=50, verbose_name='Заголовок новости')),
                ('description', models.TextField(blank=True, max_length=25, null=True, verbose_name='Описание новости')),
                ('content', models.TextField(help_text='Содержание', verbose_name='Содержание')),
                ('cover', models.ImageField(help_text='Фотографии', upload_to='covers/', verbose_name='Фото')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата', verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='users.author', verbose_name='ID автора')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID комментария')),
                ('text', models.TextField(max_length=300, verbose_name='Текст комментария')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарий',
            },
        ),
    ]
