# Generated by Django 4.1.1 on 2023-06-21 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import it_bel_app.managers.user


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "author_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID автора"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Имя автора",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email", max_length=254, verbose_name="Почта автора"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата регистрации",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID пользователя",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email",
                        max_length=254,
                        verbose_name="Почта пользователя",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата регистрации",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="Админ")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", it_bel_app.managers.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "news_id",
                    models.AutoField(
                        help_text="Уникальный идентификатор новости",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID книги",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок новости",
                        max_length=50,
                        verbose_name="Заголовок новости",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="Описание новости",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Содержание", verbose_name="Содержание"),
                ),
                (
                    "cover",
                    models.ImageField(
                        help_text="Фотографии", upload_to="covers/", verbose_name="Фото"
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата",
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="it_bel_app.author",
                        verbose_name="ID автора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
